# Site
repository: bangjaeyoung/bangjaeyoung.github.io

# Personal info
name: 방재영
title: 백엔드 개발자
email: qkdwo4613@gmail.com
website: https://jaeyoungb.tistory.com/

# Social links
github_username:  bangjaeyoung
instagram_username: qkdwodud_
# linkedin_username: bangjaeyoung

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  * 안녕하세요. 백엔드 개발자를 희망하는 방재영입니다.<br/><br/>
  
  * Lorem ipsum dolor sit amet, consectetur adipiscing elit.<br/><br/>
  
  * Nullam laoreet ligula non lorem rutrum, et tempus sapien semper.<br/><br/>
  
  * Curabitur eget nulla sed odio finibus tincidunt.<br/><br/>
  
# Skill Section
# Skill_title: Skills

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

github: [metadata]
